### ISSUE TITLE
Remove `colors` dependency?

### ISSUE THREAD

**Issue by KATT** [Floby/node-envie#6]
Reminds me a lot of this article: https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

**Comment by Floby** [comment]
I've audited `colors@1.3.0` personnally and found no such risk. Colors are nice so i'm keeping them :) sorry.

**Comment by KATT** [comment]
Why not make it an optional dependency..?

https://docs.npmjs.com/files/package.json#optionaldependencies
